# global:
#   smtp_smarthost: 'smtp:25'
#   smtp_from: 'email@example.com'
# route:
#   receiver: example-email
#   group_by: [alertname]
# receivers:
#  - name: example-email
#    email_configs:
#     - to: 'email@example.com'



#  webhook alertmanager
global:
  resolve_timeout: 10s
route:
  receiver: webhook_receiver_emailing_service
  # routes:
    # -  receiver: webhook_webhook_site # ini gak usah diaktifin
    #    continue: true
    # - receiver: webhook_container_service
    #   continue: true
receivers:
  
    - name: webhook_receiver_emailing_service
      webhook_configs:
        - url: http://example_webhook_prome:9898/api/v1/email/down # http://mailing-service:8555 # anggap 8555 port mailing service  #'https://webhook.site/7d37e2ff-560c-4279-9b23-26681123a10a' #container-service:8888
          send_resolved: false
     # - name: webhook_webhook_site # ini gak usah diaktifin, cuma buat tes di website webhook.site, kalau mau diaktifin harus sering  sering hit get endpoint url yang dikasih webhook.site
    #   webhook_configs:
    #     - url: https://webhook.site/7d37e2ff-560c-4279-9b23-26681123a10a # ganti dg url yang dikasih webhook.site (ini url buat laptopku)
    #       send_resolved: false
    # - name: webhook_container_service
    #   webhook_configs:
    #     - url: http://container-service:8888
    #       send_resolved: false