scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: docker
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.0.112:9323



    