groups:
- name: server_is_down
  rules:
  - alert: server is down
    expr: up == 0
    for: 10s #buat demo mending 10s aja
    labels:
      severity: page
    annotations:
      summary: Server(s) are down

- name: user_swarm_service
  rules:
  - alert: user swarm service/container is down
    expr: count(time()  - container_last_seen{ container_label_com_docker_compose_service=~".+"} > 10) by (container_label_com_docker_swarm_service_id, container_label_com_docker_swarm_service_name,  container_label_user_id)
    for: 5s
    labels:
      severity: page
    annotations:
      summary: user swarm service/container is down



      