
rule_files:
  - prometheus.rules.yml
  - alerting.yml


global:
  scrape_interval: 5s
  evaluation_interval: 5s

# buat alerting
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093


# buat scraping
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
# Make Prometheus scrape itself for metrics.
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']


  # Create a job for Docker daemons.
- job_name: 'docker'
  dockerswarm_sd_configs:
    - host: unix:///var/run/docker.sock
      role: nodes
  relabel_configs:
    # Fetch metrics on port 9323.
    - source_labels: [__meta_dockerswarm_node_address]
      target_label: __address__
      replacement: $1:9323
    # Set hostname as instance label
    - source_labels: [__meta_dockerswarm_node_hostname]
      target_label: instance

# Create a job for Docker Swarm containers.
- job_name: 'dockerswarm'
  dockerswarm_sd_configs:
    - host: unix:///var/run/docker.sock
      role: tasks
  relabel_configs:
    # Only keep containers that should be running.
    - source_labels: [__meta_dockerswarm_task_desired_state]
      regex: running
      action: keep
    # Only keep containers that have a `prometheus-job` label.
    - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
      regex: .+
      action: keep
    # Use the prometheus-job Swarm label as Prometheus job label.
    - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
      target_label: job


# node-exporter
- job_name: node
  static_configs:
  - targets:
      - node-exporter:9100




# - job_name: docker #  gak guna , container metrics nya lewat cadvisor
#   scrape_interval: 5s
#   static_configs:
#   - targets:
#     # - 192.168.0.112:9323
#     # - 0.0.0.0:9323 ggakbisa (127.0.0.1 jg gak bisa)
#     - 192.168.217.68:9323






    